# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-19 10:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='活动主题')),
                ('desc', models.TextField(verbose_name='活动详情')),
                ('image', models.ImageField(upload_to='image/', verbose_name='活动图片')),
                ('time', models.DateField(verbose_name='活动时间')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='通知标题')),
                ('content', models.TextField(verbose_name='通知内容')),
                ('time', models.DateTimeField(default=datetime.datetime.now, verbose_name='通知发布时间')),
            ],
            options={
                'verbose_name': '信息通知',
                'verbose_name_plural': '信息通知',
            },
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField(verbose_name='简介')),
                ('research_area', models.TextField(verbose_name='研究方向')),
                ('rules', models.TextField(verbose_name='规章制度')),
            ],
            options={
                'verbose_name': '实验室简介',
                'verbose_name_plural': '实验室简介',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='项目名称')),
                ('content', models.TextField(verbose_name='项目详情')),
                ('time', models.DateField(verbose_name='项目开始时间')),
                ('finish', models.BooleanField(default=True, verbose_name='项目是否已经完成')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='论文专著名称')),
                ('content', models.TextField(verbose_name='论文专著详情')),
                ('time', models.DateField(verbose_name='论文专著发表时间')),
            ],
            options={
                'verbose_name': '论文专著',
                'verbose_name_plural': '论文专著',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=30, verbose_name='资源名称')),
                ('author_name', models.CharField(max_length=20, verbose_name='上传者姓名')),
                ('desc', models.TextField(verbose_name='资源描述')),
                ('path', models.FileField(upload_to='uploads/', verbose_name='文件保存路径')),
                ('time', models.DateField(verbose_name='文件上传时间')),
            ],
            options={
                'verbose_name': '学习资源',
                'verbose_name_plural': '学习资源',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='学生姓名')),
                ('degree', models.CharField(choices=[('bachelor', '学士'), ('master', '硕士'), ('doctor', '博士')], max_length=10, verbose_name='学位')),
                ('graduate', models.BooleanField(default=False, verbose_name='是否毕业')),
                ('job', models.CharField(default='', max_length=50, verbose_name='毕业去向')),
                ('individual', models.TextField(verbose_name='个人简介')),
                ('photo', models.ImageField(upload_to='photo/', verbose_name='学生照片')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='教师姓名')),
                ('profession', models.CharField(choices=[('professor', '教授'), ('associate', '副教授'), ('lecturer', '讲师')], max_length=20, verbose_name='职称')),
                ('department', models.CharField(max_length=50, verbose_name='系所')),
                ('email', models.CharField(max_length=50, verbose_name='邮箱')),
                ('individual', models.TextField(verbose_name='个人简介')),
                ('photo', models.ImageField(upload_to='photo/', verbose_name='教师照片')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
            },
        ),
    ]
