# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-26 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='genre',
            field=models.CharField(choices=[('paper', '论文'), ('monograph', '专著')], max_length=30, null=True, verbose_name='科研分类'),
        ),
        migrations.AddField(
            model_name='research',
            name='prize',
            field=models.BooleanField(default=False, verbose_name='是否获奖'),
        ),
    ]
