# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-28 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_prize_studentproject_studentresearch_teacherproject_teacherresearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='图片名称')),
                ('photo', models.ImageField(upload_to='image/', verbose_name='活动图片')),
            ],
            options={
                'verbose_name': '活动图片',
                'verbose_name_plural': '活动图片',
            },
        ),
        migrations.RemoveField(
            model_name='activity',
            name='image',
        ),
        migrations.AddField(
            model_name='activity',
            name='genre',
            field=models.CharField(choices=[('study', '学习'), ('entertainment', '娱乐')], max_length=30, null=True, verbose_name='活动类型'),
        ),
        migrations.AddField(
            model_name='information',
            name='genre',
            field=models.CharField(choices=[('news', '校内新闻'), ('lecture', '讲座信息'), ('conference', '会议通知')], max_length=30, null=True, verbose_name='通知类型'),
        ),
        migrations.AddField(
            model_name='image',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Activity', verbose_name='活动'),
        ),
    ]
